language: c

sudo: false

addons:
  apt:
    packages:
      - texinfo

branches:
    only: master

install: true

script:
     - ./scripts/this-version
     - touch ChangeLog && touch NEWS
     - ./bootstrap && ./configure && make
     - src/hithere
     - prove

notifications:
     email: gunter.liszewski@gmail.com
