language: c

sudo: false

addons:
  apt:
    packages:
      - texinfo

branches:
    only: master

install: true

script:
     - touch ChangeLog && touch NEWS && ./bootstrap && ./configure && make
     - src/hithere

notifications:
     email: gunter.liszewski@gmail.com
